version: '3.8'

services:
  routeanalyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: routeanalyzer:latest
    volumes:
      - ../evaluation:/app/evaluation
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "/app/app.jar"]